name: Deploy React + Backend via FTP (seguro)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FRONT_DIR: frontend
      BACK_DIR: backend
      NODE_VERSION: 18

    steps:
      # 1. Checkout del código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      # 3. Build del frontend
      - name: Install front-end dependencies
        working-directory: ${{ env.FRONT_DIR }}
        run: npm ci

      - name: Build front-end (Vite)
        working-directory: ${{ env.FRONT_DIR }}
        run: npm run build

      # 4. Prepara backend
      - name: Install back-end dependencies (production only)
        working-directory: ${{ env.BACK_DIR }}
        run: |
          npm ci --omit=dev
          npm prune --omit=dev

      # 5. Deploy FRONTEND con usuario ftp_front
      - name: Deploy frontend to public_html
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_FRONT_HOST }}
          username: ${{ secrets.FTP_FRONT_USER }}
          password: ${{ secrets.FTP_FRONT_PASS }}
          server-dir: /
          local-dir: ${{ env.FRONT_DIR }}/dist/

      # 6. Deploy BACKEND con usuario ftp_back
      - name: Deploy backend to /backend
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_BACK_HOST }}
          username: ${{ secrets.FTP_BACK_USER }}
          password: ${{ secrets.FTP_BACK_PASS }}
          server-dir: /
          local-dir: ${{ env.BACK_DIR }}/
